language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script:
- "flake8 --ignore=F403,E501 sched"
script:
  - coverage run --omit="site-packages" tests/features/steps.py
  - nosetests --with-doctest --with-coverage -s sched
  - python manage.py runserver
  - lettuce tests
after_script:
  - coverage report -m