language: python
python:
  - "2.7"
#run a web browser
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script:
- "flake8 --ignore=F403,E501 sched"
script:
  - coverage run --omit="site-packages" unitTests.py
  - coverage report -m
  - nosetests --with-doctest -s sched
  - python manage.py runserver & lettuce tests
#after_script: