language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
before_script:
#- "flake8 --ignore=F403,E501 tests"
script:
#  - coverage run tests/features/steps.py  
#  - lettuce tests
#  - nosetests --with-doctest --with-coverage -s tests/features/app
after_script:
#  - coverage report